// Code generated by protoc-gen-go. DO NOT EDIT.
// source: aggregator.proto

package aggregator

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AggregatorRequest struct {
	SessionToken         string   `protobuf:"bytes,1,opt,name=SessionToken,proto3" json:"SessionToken,omitempty"`
	RequestBody          []byte   `protobuf:"bytes,2,opt,name=RequestBody,proto3" json:"RequestBody,omitempty"`
	URL                  string   `protobuf:"bytes,3,opt,name=URL,proto3" json:"URL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AggregatorRequest) Reset()         { *m = AggregatorRequest{} }
func (m *AggregatorRequest) String() string { return proto.CompactTextString(m) }
func (*AggregatorRequest) ProtoMessage()    {}
func (*AggregatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aggregator_d73efa607de03ac8, []int{0}
}
func (m *AggregatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregatorRequest.Unmarshal(m, b)
}
func (m *AggregatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregatorRequest.Marshal(b, m, deterministic)
}
func (dst *AggregatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregatorRequest.Merge(dst, src)
}
func (m *AggregatorRequest) XXX_Size() int {
	return xxx_messageInfo_AggregatorRequest.Size(m)
}
func (m *AggregatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AggregatorRequest proto.InternalMessageInfo

func (m *AggregatorRequest) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *AggregatorRequest) GetRequestBody() []byte {
	if m != nil {
		return m.RequestBody
	}
	return nil
}

func (m *AggregatorRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

type AggregatorResponse struct {
	StatusCode           int32             `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusMessage        string            `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	Header               map[string]string `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AggregatorResponse) Reset()         { *m = AggregatorResponse{} }
func (m *AggregatorResponse) String() string { return proto.CompactTextString(m) }
func (*AggregatorResponse) ProtoMessage()    {}
func (*AggregatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aggregator_d73efa607de03ac8, []int{1}
}
func (m *AggregatorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregatorResponse.Unmarshal(m, b)
}
func (m *AggregatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregatorResponse.Marshal(b, m, deterministic)
}
func (dst *AggregatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregatorResponse.Merge(dst, src)
}
func (m *AggregatorResponse) XXX_Size() int {
	return xxx_messageInfo_AggregatorResponse.Size(m)
}
func (m *AggregatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AggregatorResponse proto.InternalMessageInfo

func (m *AggregatorResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *AggregatorResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *AggregatorResponse) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *AggregatorResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type RediscoverSystemInventoryRequest struct {
	SystemID             string   `protobuf:"bytes,1,opt,name=SystemID,proto3" json:"SystemID,omitempty"`
	SystemURL            string   `protobuf:"bytes,2,opt,name=SystemURL,proto3" json:"SystemURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RediscoverSystemInventoryRequest) Reset()         { *m = RediscoverSystemInventoryRequest{} }
func (m *RediscoverSystemInventoryRequest) String() string { return proto.CompactTextString(m) }
func (*RediscoverSystemInventoryRequest) ProtoMessage()    {}
func (*RediscoverSystemInventoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aggregator_d73efa607de03ac8, []int{2}
}
func (m *RediscoverSystemInventoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RediscoverSystemInventoryRequest.Unmarshal(m, b)
}
func (m *RediscoverSystemInventoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RediscoverSystemInventoryRequest.Marshal(b, m, deterministic)
}
func (dst *RediscoverSystemInventoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RediscoverSystemInventoryRequest.Merge(dst, src)
}
func (m *RediscoverSystemInventoryRequest) XXX_Size() int {
	return xxx_messageInfo_RediscoverSystemInventoryRequest.Size(m)
}
func (m *RediscoverSystemInventoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RediscoverSystemInventoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RediscoverSystemInventoryRequest proto.InternalMessageInfo

func (m *RediscoverSystemInventoryRequest) GetSystemID() string {
	if m != nil {
		return m.SystemID
	}
	return ""
}

func (m *RediscoverSystemInventoryRequest) GetSystemURL() string {
	if m != nil {
		return m.SystemURL
	}
	return ""
}

type RediscoverSystemInventoryResponse struct {
	TaskURL              string   `protobuf:"bytes,1,opt,name=TaskURL,proto3" json:"TaskURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RediscoverSystemInventoryResponse) Reset()         { *m = RediscoverSystemInventoryResponse{} }
func (m *RediscoverSystemInventoryResponse) String() string { return proto.CompactTextString(m) }
func (*RediscoverSystemInventoryResponse) ProtoMessage()    {}
func (*RediscoverSystemInventoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aggregator_d73efa607de03ac8, []int{3}
}
func (m *RediscoverSystemInventoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RediscoverSystemInventoryResponse.Unmarshal(m, b)
}
func (m *RediscoverSystemInventoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RediscoverSystemInventoryResponse.Marshal(b, m, deterministic)
}
func (dst *RediscoverSystemInventoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RediscoverSystemInventoryResponse.Merge(dst, src)
}
func (m *RediscoverSystemInventoryResponse) XXX_Size() int {
	return xxx_messageInfo_RediscoverSystemInventoryResponse.Size(m)
}
func (m *RediscoverSystemInventoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RediscoverSystemInventoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RediscoverSystemInventoryResponse proto.InternalMessageInfo

func (m *RediscoverSystemInventoryResponse) GetTaskURL() string {
	if m != nil {
		return m.TaskURL
	}
	return ""
}

type UpdateSystemStateRequest struct {
	SystemUUID           string   `protobuf:"bytes,1,opt,name=SystemUUID,proto3" json:"SystemUUID,omitempty"`
	SystemID             string   `protobuf:"bytes,2,opt,name=SystemID,proto3" json:"SystemID,omitempty"`
	SystemURI            string   `protobuf:"bytes,3,opt,name=SystemURI,proto3" json:"SystemURI,omitempty"`
	UpdateKey            string   `protobuf:"bytes,4,opt,name=UpdateKey,proto3" json:"UpdateKey,omitempty"`
	UpdateVal            string   `protobuf:"bytes,5,opt,name=UpdateVal,proto3" json:"UpdateVal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSystemStateRequest) Reset()         { *m = UpdateSystemStateRequest{} }
func (m *UpdateSystemStateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSystemStateRequest) ProtoMessage()    {}
func (*UpdateSystemStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aggregator_d73efa607de03ac8, []int{4}
}
func (m *UpdateSystemStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSystemStateRequest.Unmarshal(m, b)
}
func (m *UpdateSystemStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSystemStateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateSystemStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSystemStateRequest.Merge(dst, src)
}
func (m *UpdateSystemStateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSystemStateRequest.Size(m)
}
func (m *UpdateSystemStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSystemStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSystemStateRequest proto.InternalMessageInfo

func (m *UpdateSystemStateRequest) GetSystemUUID() string {
	if m != nil {
		return m.SystemUUID
	}
	return ""
}

func (m *UpdateSystemStateRequest) GetSystemID() string {
	if m != nil {
		return m.SystemID
	}
	return ""
}

func (m *UpdateSystemStateRequest) GetSystemURI() string {
	if m != nil {
		return m.SystemURI
	}
	return ""
}

func (m *UpdateSystemStateRequest) GetUpdateKey() string {
	if m != nil {
		return m.UpdateKey
	}
	return ""
}

func (m *UpdateSystemStateRequest) GetUpdateVal() string {
	if m != nil {
		return m.UpdateVal
	}
	return ""
}

type UpdateSystemStateResponse struct {
	TaskURL              string   `protobuf:"bytes,1,opt,name=TaskURL,proto3" json:"TaskURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSystemStateResponse) Reset()         { *m = UpdateSystemStateResponse{} }
func (m *UpdateSystemStateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSystemStateResponse) ProtoMessage()    {}
func (*UpdateSystemStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aggregator_d73efa607de03ac8, []int{5}
}
func (m *UpdateSystemStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSystemStateResponse.Unmarshal(m, b)
}
func (m *UpdateSystemStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSystemStateResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateSystemStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSystemStateResponse.Merge(dst, src)
}
func (m *UpdateSystemStateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSystemStateResponse.Size(m)
}
func (m *UpdateSystemStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSystemStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSystemStateResponse proto.InternalMessageInfo

func (m *UpdateSystemStateResponse) GetTaskURL() string {
	if m != nil {
		return m.TaskURL
	}
	return ""
}

type SendStartUpDataRequest struct {
	PluginAddr           string   `protobuf:"bytes,1,opt,name=PluginAddr,proto3" json:"PluginAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendStartUpDataRequest) Reset()         { *m = SendStartUpDataRequest{} }
func (m *SendStartUpDataRequest) String() string { return proto.CompactTextString(m) }
func (*SendStartUpDataRequest) ProtoMessage()    {}
func (*SendStartUpDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aggregator_d73efa607de03ac8, []int{6}
}
func (m *SendStartUpDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendStartUpDataRequest.Unmarshal(m, b)
}
func (m *SendStartUpDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendStartUpDataRequest.Marshal(b, m, deterministic)
}
func (dst *SendStartUpDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendStartUpDataRequest.Merge(dst, src)
}
func (m *SendStartUpDataRequest) XXX_Size() int {
	return xxx_messageInfo_SendStartUpDataRequest.Size(m)
}
func (m *SendStartUpDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendStartUpDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendStartUpDataRequest proto.InternalMessageInfo

func (m *SendStartUpDataRequest) GetPluginID() string {
	if m != nil {
		return m.PluginAddr
	}
	return ""
}

type SendStartUpDataResponse struct {
	ResponseBody         []byte   `protobuf:"bytes,1,opt,name=ResponseBody,proto3" json:"ResponseBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendStartUpDataResponse) Reset()         { *m = SendStartUpDataResponse{} }
func (m *SendStartUpDataResponse) String() string { return proto.CompactTextString(m) }
func (*SendStartUpDataResponse) ProtoMessage()    {}
func (*SendStartUpDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aggregator_d73efa607de03ac8, []int{7}
}
func (m *SendStartUpDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendStartUpDataResponse.Unmarshal(m, b)
}
func (m *SendStartUpDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendStartUpDataResponse.Marshal(b, m, deterministic)
}
func (dst *SendStartUpDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendStartUpDataResponse.Merge(dst, src)
}
func (m *SendStartUpDataResponse) XXX_Size() int {
	return xxx_messageInfo_SendStartUpDataResponse.Size(m)
}
func (m *SendStartUpDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendStartUpDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendStartUpDataResponse proto.InternalMessageInfo

func (m *SendStartUpDataResponse) GetResponseBody() []byte {
	if m != nil {
		return m.ResponseBody
	}
	return nil
}

func init() {
	proto.RegisterType((*AggregatorRequest)(nil), "AggregatorRequest")
	proto.RegisterType((*AggregatorResponse)(nil), "AggregatorResponse")
	proto.RegisterMapType((map[string]string)(nil), "AggregatorResponse.HeaderEntry")
	proto.RegisterType((*RediscoverSystemInventoryRequest)(nil), "RediscoverSystemInventoryRequest")
	proto.RegisterType((*RediscoverSystemInventoryResponse)(nil), "RediscoverSystemInventoryResponse")
	proto.RegisterType((*UpdateSystemStateRequest)(nil), "UpdateSystemStateRequest")
	proto.RegisterType((*UpdateSystemStateResponse)(nil), "UpdateSystemStateResponse")
	proto.RegisterType((*SendStartUpDataRequest)(nil), "SendStartUpDataRequest")
	proto.RegisterType((*SendStartUpDataResponse)(nil), "SendStartUpDataResponse")
}

func init() { proto.RegisterFile("aggregator.proto", fileDescriptor_aggregator_d73efa607de03ac8) }

var fileDescriptor_aggregator_d73efa607de03ac8 = []byte{
	// 696 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x4e, 0x1b, 0x3d,
	0x10, 0x4d, 0x08, 0xe1, 0xfb, 0x32, 0xa1, 0x02, 0x0c, 0x85, 0x65, 0x5b, 0xd1, 0x60, 0x55, 0x15,
	0x57, 0x7b, 0x41, 0x55, 0xb5, 0xb4, 0x45, 0x6a, 0x48, 0xf8, 0x53, 0x41, 0x54, 0xbb, 0x09, 0x57,
	0xbd, 0x31, 0xec, 0x10, 0xa2, 0x6c, 0xec, 0xd4, 0x76, 0x22, 0xe5, 0xad, 0xfa, 0x0e, 0x7d, 0x93,
	0x3e, 0x49, 0xb5, 0x7f, 0xc9, 0xe6, 0xaf, 0x74, 0x93, 0x3b, 0xfb, 0xd8, 0x73, 0xe6, 0xcc, 0xd9,
	0x19, 0x27, 0xb0, 0xce, 0x1a, 0x0d, 0x89, 0x0d, 0xa6, 0x85, 0xb4, 0x3a, 0x52, 0x68, 0x41, 0x5b,
	0xb0, 0x51, 0x1e, 0x60, 0x36, 0xfe, 0xe8, 0xa2, 0xd2, 0x84, 0xc2, 0xaa, 0x83, 0x4a, 0x35, 0x05,
	0xaf, 0x89, 0x16, 0x72, 0x23, 0x5b, 0xca, 0x1e, 0x14, 0xec, 0x11, 0x8c, 0x94, 0xa0, 0x18, 0x5d,
	0x3f, 0x11, 0x6e, 0xdf, 0x58, 0x2a, 0x65, 0x0f, 0x56, 0xed, 0x24, 0x44, 0xd6, 0x21, 0x57, 0xb7,
	0xaf, 0x8c, 0x5c, 0x10, 0xec, 0x2f, 0xe9, 0xef, 0x2c, 0x90, 0x64, 0x36, 0xd5, 0x11, 0x5c, 0x21,
	0xd9, 0x03, 0x50, 0x9a, 0xe9, 0xae, 0xaa, 0x08, 0x17, 0x83, 0x64, 0x79, 0x3b, 0x81, 0x90, 0xd7,
	0xf0, 0x2c, 0xdc, 0x5d, 0xa3, 0x52, 0xac, 0x81, 0x41, 0xb2, 0x82, 0x3d, 0x0a, 0x92, 0xf7, 0xb0,
	0xf2, 0x88, 0xcc, 0x45, 0x69, 0xe4, 0x4a, 0xb9, 0x83, 0xe2, 0xe1, 0x2b, 0x6b, 0x32, 0x95, 0x75,
	0x11, 0xdc, 0x38, 0xe5, 0x5a, 0xf6, 0xed, 0xe8, 0x3a, 0x21, 0xb0, 0x7c, 0xe7, 0x97, 0xb0, 0x1c,
	0x94, 0x10, 0xac, 0xcd, 0x23, 0x28, 0x26, 0xae, 0xfa, 0xa5, 0xb4, 0xb0, 0x1f, 0xf9, 0xe0, 0x2f,
	0xc9, 0x16, 0xe4, 0x7b, 0xcc, 0xeb, 0xc6, 0x5a, 0xc2, 0xcd, 0xc7, 0xa5, 0x0f, 0x59, 0xfa, 0x1d,
	0x4a, 0x36, 0xba, 0x4d, 0x75, 0x2f, 0x7a, 0x28, 0x9d, 0xbe, 0xd2, 0xd8, 0xbe, 0xe4, 0x3d, 0xe4,
	0x5a, 0xc8, 0x7e, 0x6c, 0xb0, 0x09, 0xff, 0x47, 0x27, 0xd5, 0x88, 0x74, 0xb0, 0x27, 0x2f, 0xa1,
	0x10, 0xae, 0x7d, 0xf3, 0x42, 0xf6, 0x21, 0x40, 0x8f, 0x61, 0xff, 0x2f, 0xec, 0x91, 0xa1, 0x06,
	0xfc, 0x57, 0x63, 0xaa, 0xe5, 0x13, 0x84, 0xec, 0xf1, 0x96, 0xfe, 0xcc, 0x82, 0x51, 0xef, 0xb8,
	0x4c, 0x63, 0x18, 0xeb, 0x68, 0xa6, 0x31, 0x56, 0xb5, 0x07, 0x10, 0x25, 0xaa, 0x0f, 0x74, 0x25,
	0x90, 0x11, 0xd5, 0x4b, 0xb3, 0x55, 0x5f, 0x46, 0x9f, 0x7c, 0x08, 0xf8, 0xa7, 0x61, 0xd6, 0xaf,
	0x18, 0xfa, 0x5c, 0xb0, 0x87, 0xc0, 0xf0, 0xf4, 0x96, 0x79, 0x46, 0x3e, 0x79, 0x7a, 0xcb, 0x3c,
	0xfa, 0x0e, 0x76, 0xa7, 0x28, 0x7e, 0xb2, 0x52, 0x0d, 0xdb, 0x0e, 0x72, 0xd7, 0xd1, 0x4c, 0xea,
	0x7a, 0xa7, 0xca, 0x34, 0x4b, 0x98, 0xff, 0xcd, 0xeb, 0x36, 0x9a, 0x7c, 0x68, 0x7e, 0xbc, 0xf7,
	0xa5, 0xdc, 0x74, 0x50, 0x32, 0xdd, 0x14, 0x3c, 0x36, 0x7f, 0x00, 0x24, 0x7a, 0xbe, 0xd6, 0xef,
	0x60, 0x54, 0x66, 0x12, 0xa2, 0x9f, 0x60, 0x67, 0x22, 0x6b, 0x24, 0x75, 0x6c, 0x60, 0xb2, 0x13,
	0x03, 0x73, 0xf8, 0xab, 0x08, 0x30, 0xec, 0x59, 0x72, 0x02, 0xcf, 0xcf, 0x51, 0xc7, 0x40, 0x53,
	0x70, 0x07, 0x65, 0xaf, 0x79, 0x8f, 0x84, 0x58, 0x13, 0x23, 0x6b, 0x6e, 0x4e, 0xe9, 0x76, 0x9a,
	0x21, 0x87, 0x90, 0xb7, 0x51, 0xa1, 0x4e, 0x13, 0xf3, 0x05, 0x36, 0x1d, 0xd4, 0x55, 0x7c, 0x60,
	0x5d, 0x4f, 0x9f, 0x08, 0xa1, 0x6f, 0x64, 0x30, 0x26, 0xff, 0xce, 0xe0, 0xc2, 0xee, 0xcc, 0x26,
	0x25, 0xfb, 0xd6, 0x53, 0xe3, 0x61, 0x52, 0xeb, 0xc9, 0x1e, 0xa7, 0x19, 0x72, 0x05, 0x1b, 0x13,
	0x8d, 0x41, 0x76, 0xad, 0x59, 0xed, 0x6d, 0x9a, 0xd6, 0xcc, 0x3e, 0xa2, 0x19, 0x52, 0x86, 0xad,
	0xb2, 0xeb, 0x26, 0xdd, 0x16, 0x5d, 0x99, 0xce, 0xec, 0x2a, 0xec, 0xf8, 0x1f, 0xcc, 0xf3, 0x16,
	0x62, 0x29, 0xc3, 0xd6, 0xd8, 0x67, 0x9f, 0x47, 0x48, 0x58, 0xea, 0xa2, 0x2c, 0x55, 0xf4, 0x70,
	0x41, 0x96, 0xcf, 0xb0, 0x56, 0x91, 0x98, 0xd0, 0x92, 0x2a, 0xfa, 0x18, 0xd6, 0x47, 0x2d, 0x45,
	0x95, 0x26, 0xfc, 0x08, 0x56, 0x13, 0x5e, 0xa6, 0xd5, 0x3d, 0x5a, 0x7d, 0xaa, 0xe8, 0x0a, 0x6c,
	0x97, 0x5d, 0xf7, 0xd4, 0xc3, 0x36, 0x72, 0xad, 0x6a, 0x62, 0x2e, 0x92, 0x0b, 0x78, 0x61, 0x63,
	0x5b, 0xf4, 0x30, 0xe6, 0x39, 0x93, 0xa2, 0x3d, 0x17, 0xd3, 0x29, 0x18, 0xc1, 0x33, 0x10, 0x13,
	0xdd, 0x3c, 0xcc, 0x45, 0xe3, 0xc0, 0x9b, 0x29, 0x2f, 0xc3, 0x82, 0xa4, 0x83, 0xa9, 0xa9, 0x08,
	0xce, 0xf1, 0xde, 0xef, 0xb2, 0x6b, 0xd4, 0x8f, 0xc2, 0x55, 0x29, 0x1f, 0xad, 0x73, 0xd4, 0xe3,
	0x14, 0x69, 0x18, 0xce, 0x60, 0x6d, 0xec, 0xe9, 0x26, 0x3b, 0xd6, 0xf4, 0x9f, 0x10, 0xd3, 0xb0,
	0x66, 0xbc, 0xf2, 0x34, 0x73, 0xb7, 0x12, 0xfc, 0xb1, 0x7a, 0xfb, 0x27, 0x00, 0x00, 0xff, 0xff,
	0x94, 0xda, 0x38, 0xf0, 0x6c, 0x09, 0x00, 0x00,
}
